### ISSUE TITLE
Camera Movement is very slow when using a controller

### ISSUE THREAD

**Issue by sondaismith** [zamorikan/Astroball#11]
Adjust default camera speed while using a controller + allow adjustment from pause menu?

**Comment by zamorikan** [comment]
there's a twofold issue here - one is that there's a calculation that's applied to the speed of the camera in the options menu... except because the options menu starts as an inactive object, the script doesn't fire until you open the options menu. and then when you do it actually just makes the camera movement even slower lmao.

second part of this is that the camera movement when applied via the new input system has to have a multiplier applied when being used for a controller. this can be tweaked in the input system object under Assets/Input System/AstroballControls.InputActions under the movement action, i thinkt there's a "Multiplier" or something condition on it.

**Comment by zamorikan** [comment]
Fixed with merge  from 11-slow-camera-movement - ignore the above revert as that was a mistake.
